# Generated by Django 6.1.1 on 2026-09-08 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(db_index=True, max_length=30, unique=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_REVIEW', 'Ready For Review'), ('DONE', 'Done')], db_index=True, default='TODO', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status', 'is_deleted'], name='tasks_task_project_e8cf5d_idx'), models.Index(fields=['project', 'assignee', 'is_deleted'], name='tasks_task_project_c43abb_idx'), models.Index(fields=['project', 'priority', 'is_deleted'], name='tasks_task_project_0d370f_idx'), models.Index(fields=['project', 'created_at', 'is_deleted'], name='tasks_task_project_bce466_idx'), models.Index(fields=['assignee', 'is_deleted'], name='tasks_task_assigne_33319a_idx')],
                'constraints': [models.UniqueConstraint(fields=('task_key',), name='unique_task_key'), models.UniqueConstraint(fields=('project', 'sequence_number'), name='unique_project_task_sequence'), models.CheckConstraint(condition=models.Q(('status__in', ['TODO', 'IN_PROGRESS', 'READY_FOR_REVIEW', 'DONE'])), name='valid_task_status'), models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH', 'URGENT'])), name='valid_task_priority')],
            },
        ),
    ]
