# Generated by Django 6.1.1 on 2026-09-08 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_TEAM_ADDED', 'Team Assigned to Project'), ('PROJECT_TEAM_REMOVED', 'Team Removed from Project'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Details Updated'), ('TASK_ASSIGNED', 'Task Assignee Changed'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('COMMENT_ADDED', 'Comment Added'), ('COMMENT_DELETED', 'Comment Deleted')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
