# Generated by Django 6.1.1 on 2026-09-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project', 'timestamp'], name='activities__project_f2f267_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['task', 'timestamp'], name='activities__task_id_26940f_idx'),
        ),
    ]
